### ISSUE TITLE
::MAIN: Unable to locate a section with subsection:UNCAT enabled in your autoProcessMedia.cfg, exiting!

### ISSUE THREAD

**Issue by sv2241** [clinton-hall/nzbToMedia#1029]
::MAIN: Unable to locate a section with subsection:UNCAT enabled in your autoProcessMedia.cfg, exiting!" 
Uncat category is there but it's not enabled so why am I getting these errors?
Sickbeard runs on a separate host (10.1.10.7/ubuntu) than transmission and nzbtomedia (localhost/freenas)
SickGear > Settings > Post-processing > "Completed TV downloads": /downloads/transmission/complete/tv and "Process episode method": move

nzbtomedia.log --> https://gist.github.com/sv2241/c13f0b98b0e4348afc11b70dbffe671b
autoProcessMedia.cfg --> https://gist.github.com/sv2241/be83b3ca42116c595983e4ac9934140c

**Comment by clinton-hall** [comment]
sorry for the delay. The links you posted above are not valid...

This error usually happens because there is no category defined (passed in to nzbToMedia) and it cannot find the category from the folder structure.

so in sickrage, you should tell this to send to transmission and download to <download_directory>/tv
then in autoProcessMedia.cfg you need to have
```
[SickBeard]
    [[tv]]
        enabled = 1
```
