### ISSUE TITLE
Extra move/copy/link step for torrents, why?

### ISSUE THREAD

**Issue by bendavid** [clinton-hall/nzbToMedia#1031]
I was trying to understand the purpose of a separate output directory and the initial move/copy/link step for torrent downloads.  Why not just call sickrage/couchpotato and let them deal with things directly from the initial torrent download location?  If the goal is just to have separate download locations for the different sources, this is already possible by overriding the torrent download directory in the sickrage or couchpotato settings.

**Comment by clinton-hall** [comment]
the reasoning here is that this script supported linking before it was available in CouchPotato/SickBeard.

so the idea was to leave seeding files alone and let CP/SB process the copied/moed/linked files only and not touch the seeding files.

Also, where single file downloads exists, calling CP/SB to process the entire directory (where most files had already been processed) was problematic.

This script should be cleaning up any intermediary files/folders on completion. The main downside here is that it can take longer if you have this set to copy (or move to a different file system).

You can set output directory to input directory and since the files already exists, this doesn't do anything... I believe this is now working, despite not been my preferred or recommended process.
