### ISSUE TITLE
Feature Request: disable extraction for failed download and different extract options for NZB vs torrent

### ISSUE THREAD

**Issue by ladude626** [clinton-hall/nzbToMedia#1129]
I have a 2 feature request here:

1) Even if extract=1 is enable, it's a waste of time/resource to extract if a download is marked as failed.

2) Currently "extract" option is available for sickrage/couchpotato/headphone. I think it's more useful to have the "extract" option in NZBget/SAB/torrent. I use NZBGET/SAB and they handle extraction very well don't need nzbToMedia to handle extraction. But torrent clients do not (for example rtorrent runs extraction AFTER running post-processing script) and need to enable "extract" for them. Would be nice to have separate extract options.

**Comment by clinton-hall** [comment]
For point 1. I see where you are coming from, but this functionality was specifically requested. There are some (few) possible issues where a download might fail, but the video can still be extracted. e.g. if the download fails due to the samples or meta data being missing, but the entire video archive is present.

In these few occurrences,  the downloader won't attempt to extract, but if we can extract the video and verify that it is playable, then this saves having to download the entire video again.

For item 2. The reason this was done per category only some media managemnt tools supported their own extraction etc.
If the downloader itself handles extraction well, then this step will be over-looked by nzbToMedia since the extraction has already happened. nzbToMedia should only extract if the download has failed to extract (or has not attempted to).

**Comment by ladude626** [comment]
Would it possible to add an option to disable/enable extraction for failed download (#1) ?

**Comment by clinton-hall** [comment]
Ok.. I should be able to do this... This really only applies to nzb Downloaders?

**Comment by ladude626** [comment]
For me just nzb Downloaders but don't know if it'll also be useful for torrent downloaders.

**Comment by clinton-hall** [comment]
Try updating to latest nightly... then set 
```
[General]
   no_extract_failed = 1
```

**Comment by ladude626** [comment]
It worked. Thanks!
