### ISSUE TITLE
Excessive Transcode Time

### ISSUE THREAD

**Issue by mediaman88** [clinton-hall/nzbToMedia#1157]
I have successfully installed nzbtoMedia on my Synology DS1815+ and attempted to remux/change containers from MKV to MP4 using the transcode feature.   I am not expert on transcoding but research has told me that I simply want to change the containers without touching anything.  

I have it set to use the MP4-scene-release setting.  The first file was a 1.3GB MKV that took about 4 hours.  That seems very excessive, I've never used ffmpeg directly via command line but my understanding is that a file that size should only take a few minutes maximum even with the Synology.

Can anyone assist in what settings I could use to simply change containers?

Thanks

**Comment by clinton-hall** [comment]
Ok, the issue is that the mp4-scene release has specific quality settings that it is trying to force, and therefore it was transcoding the video. I don't have a preset to just convert the container (although I probably should!!)

If you try these custom settings, this should work.
```
    outputDefault =
    #### Define custom settings below.
    outputVideoExtension = .mp4
    outputVideoCodec = libx264
    VideoCodecAllow = libx264,h264,h.264,AVC,avc,mpeg4,msmpeg4,MPEG-4,mpeg2video
    outputVideoPreset = 
    outputVideoResolution = 
    outputVideoFramerate = 
    outputVideoBitrate =
    outputVideoCRF = 
    outputVideoLevel = 
    outputAudioCodec = dts
    AudioCodecAllow = libfaac,dts,ac3,mp2,mp3
    outputAudioChannels = 8
    outputAudioBitrate =
    outputAudioTrack2Codec =
    AudioCodec2Allow = 
    outputAudioTrack2Channels =  
    outputAudioTrack2Bitrate = 
    outputAudioOtherCodec = ac3
    AudioOtherCodecAllow = libfaac,dts,ac3,mp2,mp3
    outputAudioOtherChannels = 8
    outputAudioOtherBitrate = 
    outputSubtitleCodec = mov_text
```

Or even just the following
```
    outputDefault =
    #### Define custom settings below.
    outputVideoExtension = .mp4
    outputVideoCodec = copy
    VideoCodecAllow = 
    outputVideoPreset = 
    outputVideoResolution = 
    outputVideoFramerate = 
    outputVideoBitrate =
    outputVideoCRF = 
    outputVideoLevel = 
    outputAudioCodec = copy
    AudioCodecAllow = 
    outputAudioChannels = 
    outputAudioBitrate =
    outputAudioTrack2Codec =
    AudioCodec2Allow = 
    outputAudioTrack2Channels =  
    outputAudioTrack2Bitrate = 
    outputAudioOtherCodec = copy
    AudioOtherCodecAllow = 
    outputAudioOtherChannels = 
    outputAudioOtherBitrate = 
    outputSubtitleCodec = mov_text
```

This last setup just forces it to always copy the streams (except subtitles which can only be mov_text for .mp4

**Comment by mediaman88** [comment]
Thank you!  This worked perfectly!

Now if I could just find a way to remux the other 1,500 I have spread out across 100 directories.   Do you know of an easy way to do that? :)

**Comment by clinton-hall** [comment]
It is possible to run nzbToMedia/TorrentToMedia manually, have it search through the directories... However I like to warn against doing this without first taking safety steps (I don't want you saying my script destroyed your library).

So, What I recommend is having a backup of your library and/or copying a section at a time to be remuxed.

Now that you have a backup/or a small copy of files to be remuxed, you will need to:
set
```
[CouchPotato]
    [[movie]]
        watch_dir = <path to movies to be remuxed>
```
ideally this path should not be in the CP manage folder, as this would break postprocessing to CP.
Again, moving a small batch of files at a time is best way here.

Now when to manually run nzbTomedia it should find movies in this path and (assuming each movie is in it's own sub-directory) process each movie 1 at a time, remuxing, and passing to CouchPotato to be renamed to the media directory.

This final step is where things might be an issue, if CP gives an error due to the movie already existing at same quality...


Try it with a small batch and see. If it works, and you are confident you can turn it loose on larger batches...
