### ISSUE TITLE
Question: NZBtoMedia - SickRage

### ISSUE THREAD

**Issue by HPMSGEN8** [clinton-hall/nzbToMedia#1163]
Hi Clinton

First off i want to say thanks for this little script / tool as it works 100% once it is setup :)

I finally got my setup working but now i am getting some messages about 2 times.

1. There is no version number getting found:

`[12:34:13] [ERROR]::MAIN: Unknown current version number, don't know if we should update or not`

2. After installing ffmpeg and setting it up i am getting this now. 

`/volumeX/@appstore/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)`

`/volumeX/@appstore/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)`

`[12:34:15] [INFO]::TRANSCODER: Checking [Bobs.Burgers.S07E08.HDTV.x264-FLEET.mkv] for corruption, please stand by ...`

`/volumeX/@appstore/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)`

`/volumeX/@appstore/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)`

`[12:34:15] [INFO]::TRANSCODER: SUCCESS: [Bobs.Burgers.S07E08.HDTV.x264-FLEET.mkv] has no corruption.`

Is there an fix to this or can i ignore this. I am running this on my Synology.

Thanks

**Comment by clinton-hall** [comment]
the first error can be fixed by cloning the script using git, and ensuring that when the script is executed `git` is available in the system `PATH`

i.e. if this is called from Transmission, transmission's init script probably needs the git binary location added to PATH
e.g. if git is at /usr/local/bin/git in the Transmission init, you need to add `export PATH=$PATH:/usr/local/bin` near the start.

The second error suggests the libstdc++.so.6 version does not match the version that was used to compile the ffmpeg binary. This actually doesn't stop anything, it is just an annoyance. 
For solution you might want to ask at synocommunity... you may need to export LD_LIBRARY_PATH so that the `/volumeX/@appstore/ffmpeg/lib` is listed before `/lib` or perhaps the bianry needs to be compiled with static links etc...

**Comment by HPMSGEN8** [comment]
Thanks for the reply. I am new to this can you maybe point me in the right location to add the first one please.

for the second issue i will ask them.

Thanks alot.

**Comment by clinton-hall** [comment]
I'm not familiar with Syno. 
What downloaded are you using to call TorrentToMedia/nzbToMedia?
That downloaded should have an init script... in that script you will need to add the export line at the top following the hash-bang and then restart the app.

**Comment by clinton-hall** [comment]
As far as cloning with git, how have you installed nzbToMedia on your Syno box?

**Comment by cytec** [comment]
@HPMSGEN8 assuming that you installed nzbget wich already comes with nzbToMedia included, just switch to `/usr/local/nzbget/share/nzbget/scripts/nzbToMedia` and run `/usr/local/git/bin/git pull` there to update.

If you installed it manually you either have to download it again, or change the path so it matches your setup ;)

for the ffmpeg error see the issue you opened over at synocommunity: https://github.com/SynoCommunity/spksrc/issues/2593

**Comment by HPMSGEN8** [comment]
I have SickBreard-Custom installed and using SABNZDB as the provider. I copied the nzbToMedia from the repo to the Contrib Folder. I did not use git pull or git clone as this did not work for me.

**Comment by cytec** [comment]
well if you use that, you should have the latest version available for the fork you are using. Since SB-custom is a self updating SPK. might be an error with those scripts...

how about downloading them from here again and try with them?

**Comment by HPMSGEN8** [comment]
i am doing this all again now to see what happens
