### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by pecinko** [clinton-hall/nzbToMedia#1183]
May I suggest doing a conversion before IMDB lookup is performed? This way we can have converted video even if IMDB search yields no results or other some other post process issue pops up.

E.G. - I have added a movie to nzbGet manually and since CP did not respond properly to nzbToMedia script failed before conversion.

Thanks, P.

**Comment by clinton-hall** [comment]
so you want transcoding to proceed even if CP doesn't respond, or we fail to determine the IMDB?

**Comment by pecinko** [comment]
Yes. We can't do full post processing if IMDb data is not available but it would be helpful to have video converted to MP4.

**Comment by clinton-hall** [comment]
Ok, so this will go on to do extraction, corruption checks, and transcoding even when the server is not found to be running **only if** you have not set a CouchPotato api in the .cfg for [CouchPotato] or for [SickBeard]/[NZBDrone] you have not specified username/apikey.

The imdb data checks should not halt the processing.

If you have set CP apikey, and CP is found not to respond, the script will still exit. This change simply allows for you to use the transcoder if you don't intend CP to do final renaming. (same is true for SickBeard/Sonarr).

This will also likely end in some form of post-process failure (after transcoding) as the attempts to send to CP/SB/Sonarr etc will fail.

Please update to latest nightly branch and test.

**Comment by pecinko** [comment]
Thanks. We are on a vacation ATM, I'll test and report back as soon as we return.

**Comment by pecinko** [comment]
Ok, just noticed this will only only if CP and Sonarr API is not used.  Although this is very useful in case integration is not used, it's a deal breaker for my household. Thanks anyway, your work is much appreciated.

**Comment by clinton-hall** [comment]
If you use Sonarr/CP integration, this always has worked. I.e. the standard process is to Transcode before passing to Sonarr/CP.

I have recently fixed the issue where PP failed due to OMDB api being down, and I now allow you to transcode even if you are not actually using SB/Sonarr/CP etc... the only likely issue here is when  Sonarr/CP failed to respond because they were temporarily down, then you would get the download failed notification in NZBGet (I use the emailer to let me know)  then you restart Sonarr/CP and in NZBGet you select "postprocess again" and everything should complete fine (transcode and pass off to Sonarr/CP).
