### ISSUE TITLE
utorrent linux, web ui not responding

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1221]
So i've noticed something recently (hence looking at other possible torrent clients) that i'm not sure why its occuring. 

When i disabled using nTM, utorrent runs find for days with no apparent issues.
with nTM enabled, i've noticed when there are many jobs completed quickly, the web ui seems to stop responding. utorrent is still download etc in the background, logs are updating etc but the web ui (and consequently, API calls) fail to respond. 
This seems to occur frequently when there are more than a handful of completed jobs running. each time i've noticed it, i can see a number of stacked up nTM processes.

Since I use php api scripts to manage size limits, blacklist word nuking and a few other things that I haven't seen in any other clients, i'd like to get this working reliably. 

I'm not sure where to start with troubleshooting of what is occuring.

utorrent linux (latest, which isn't saying much)
opensuse 42.2
nTM latest

**Comment by clinton-hall** [comment]
Does utorrent linux provide any logs?
nTM does prevent multiple instances trying to process at once by placing each postrocess event on hold until the previous event has finished etcc.... so if you keep piling them on top of each other these could get held for some time. But I still wouldn't expect this to be indefinite.

What I may be able to do is modify this so that instead of pausing the just downloaded torrent (Pause seeding) I could set this to pause ALL torrents until the postprocess event is finished (this would stop another download finishing and startinf post-processing on top) and then resume afterwards?

the down-side to this is a NET delay in downloads....

**Comment by mgaulton** [comment]
So checking just now, UI unresponsive. grabbing logs

**Comment by mgaulton** [comment]
https://gist.github.com/mgaulton/3e576619d016e09f63b9d04c29054593

**Comment by mgaulton** [comment]
if I could figure out how to make rtorrent do what i want, this would be less of an issue lol

**Comment by mgaulton** [comment]
So at an intermediate mitigation, i have a monitor script that after 5 UI failures, restarts utorrent. This makes things interesting because if i don't flush the resume database at this point, it will rerun nTM on startup, which means many possible jobs get loaded and i got a screen full of "Waiting for existing session to end" and the monitor script is now waiting right there :)
