### ISSUE TITLE
nzbToMedia + nzbGet + SMB/NFS

### ISSUE THREAD

**Issue by piejanssens** [clinton-hall/nzbToMedia#1231]
Right now my whole setup runs on a Synology NAS.
I'd like to move the nzbGet instance to my powerful windows machine (faster downloads, way faster repairs).
So nzbToMedia will also move to my windows instance. 

My question is, is it nzbGet or nzbToMedia that will move the files from the nzbget category directory to the destination location on my NAS being /volume1/video/movies or /volume1/video/tv for example?

**Comment by Vanhecke** [comment]
> is it nzbGet or nzbToMedia that will move the files from the nzbget category directory to the destination location 

It would be SickRage doing that - during the `NzbToSickBeard.py` script according to the "Location" setting in SickRage (this can be changed per show).
You will notice that in the NZBGet webui it will take a bit longer for the NZBGet postprocessing to complete because NZBGet is waiting for nzbToMedia to finish, and nzbToMedia is waiting for SickRage to finish copying the file over your network.

You could also set the "temporary" NZBGet folder on the Windows machine and the NZBGet "completed" folder on the NAS. Then NZBGet will extract to the NAS.

It would probably be easier to also set SickRage on your windows computer.

**Comment by piejanssens** [comment]
Sorry that it wasn't clear, but if I put nzbget on my windows instance I would also install CP and SR alongside it. So I guess it's CP and SR who are moving it to the destination folder, I hope they both support SMB for that matter then.

**Comment by clinton-hall** [comment]
Yes, this would be the easier option... Everything on Windows. Just moving final files to NFS or a Mounted Network drive location.
if you were to keep SR and CP on the NAS, then you would need to configure the option "Mount_points" in nzbToMedia. But ultimately the move of files is done by CP and SR.
