### ISSUE TITLE
Change subtitle logging to INFO level.

### ISSUE THREAD

**Issue by bengalih** [clinton-hall/nzbToMedia#1296]
Could we get the following changed in nzbMediaUtil.py:

`logger.error("Attempting to download subtitles for {0}".format(filename), 'SUBTITLES')`

to

`logger.info("Attempting to download subtitles for {0}".format(filename), 'SUBTITLES')`

IMHO we should have some logging information that a subtitle was attempted and shouldn't assume that lack of any log means we successfully got a subtitle.

(after all how to distinguish between trying and succeeding and not being configured to try at all ).

**Comment by clinton-hall** [comment]
I don't see this error log...

`    logger.debug("Attempting to download subtitles for {0}".format(filename), 'SUBTITLES')`

is followed by

`        logger.error("Failed to download subtitles for {0} due to: {1}".format(filename, e), 'SUBTITLES')`
once it fails.

So we have debug logging on the attempt to download.
Are you asking this to be changed from debug to info?

**Comment by bengalih** [comment]
Yeah that was exactly it...I wanted to see the attempt at the info level as I think it is an important step (if you care about subtitles) to be directly notified about. thanks
