### ISSUE TITLE
Transcoding sends original file instead of transcoded file 

### ISSUE THREAD

**Issue by Hylas01** [clinton-hall/nzbToMedia#1351]
I can see the MP4 and the MKV in the directory but as soon as the renamer is called it takes the mkv instead of the mp4.

I saw  a similar thread from 2015.  The solution was to add processOutput = 1 to the transcode section, but this produces an error.   If I change the output video path, then couchpotato doesn't pick up the subtitles.

**Comment by clinton-hall** [comment]
You can try setting 
`duplicate = 0`
which will remove the original file.

Otherwise you can set the outputVideoPath and then set processOutput. As you indicate, this will not pick up the original subs, but there are options to embed subs, extract subs, and to specify a different sub directory.
Do you have `allSubLanguages = 1` set?
