### ISSUE TITLE
qbitorrent guide

### ISSUE THREAD

**Issue by poplolnman** [clinton-hall/nzbToMedia#1365]
can this be used with qbitorrent?

**Comment by clinton-hall** [comment]
yes.
https://github.com/clinton-hall/nzbToMedia/issues/1300

**Comment by poplolnman** [comment]
lots to read :), thank you for the link! i also have another question, but i probably overlooked it. i am using medusa and tried to setup up nzbtomedia with it. how does nzbmedia contact medusa?

**Comment by clinton-hall** [comment]
Medusa integration is the same as SickBeard ans SickRage etc.

**Comment by poplolnman** [comment]
oh so for the api key and whatnot, i use medusas'?

**Comment by poplolnman** [comment]
yea, i messed up on some of the steps, thank you for working with me!

**Comment by clinton-hall** [comment]
I don't think Medusa uses api key for this part... for the renaming etc.
For Medusa, set the user name and password you use to log in to the web UI.

**Comment by clinton-hall** [comment]
if no user/pass, try leaving these blank and tell me what it does. I can't remember exactly, but I have a suspicion that these won't work without user/pass...

**Comment by poplolnman** [comment]
ok, do i leave on auto processing or turn it off? just want to make sure

**Comment by poplolnman** [comment]
sorry if it is a simple question and seems stupid to ask. just not the best at this kind of things...

**Comment by clinton-hall** [comment]
so I just noticed (or just remembered) that Medusa have actually linked the setup details in my wiki
https://github.com/pymedusa/Medusa/wiki/NZBtoMedia

that guide should give you most of what is needed.

additionally, in my Wiki for SickBeard I explain how to configure SickBeard's renaming
https://github.com/clinton-hall/nzbToMedia/wiki/sickbeard
Most of this should be similar, althought the names of config items may have changed.

In essence, you want to configure all of the naming options and directories, but you want to set it so that it doesn't automatically scan (nzbToMedia will tell it when, and what, to scan)
