### ISSUE TITLE
How to use nzbToMedia only for some categories with nzbget?

### ISSUE THREAD

**Issue by MarioCaires** [clinton-hall/nzbToMedia#1372]
I am trying to setup this script only for TV Category, however when I download a movie (Movie Category), nzbget tries to run this script after download and fails!
In nzbget I have the "extension" nzbtomedia enabled in the TV Category, but no "extensions" configured for Movie Category, however nzbtomedia still runs after downloading a Movie...
Anyone knows how to correctly configure this script with nzbget just for one or some Categories but not all?

Thanks in advance!

**Comment by clinton-hall** [comment]
There are "generic" scripts that are run for non-category downloads.
NZBGet settings, Extensions Scripts, Extensions.
In this case be sure nzbToMedia.py is not added here.

Otherwise to define a category, go to NZBGet, settings, Categories,
For each category define Category<n>.name, and Category<n>.Extensions

So 
Category1.Name = TV
Category1.Extensions = nzbToMedia.py

Category2.Name = Movie
Category2.Extensions = 

Or, if you don't want to define "Movie" category, leave it out... but be sure to Remove nzbToMedia.py from the NZBGet settings, Extensions Scripts, Extensions
