### ISSUE TITLE
nzbtomedia main Category watch folder required?

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [clinton-hall/nzbToMedia#1385]
just trying to optimise my config files, I noticed do I even need to have `watch_dir` set in the 

[SickBeard]
     [[sickchill]]

section of the config file? (would this be considered as a 3rd DL location for this category?) [`/Users/USER/Downloads/NZB Downloads/Completed`]

because I have my NZB root dir set in `default_downloadDirectory` within [Nzb] section (`/Users/USER/Downloads/NZB Downloads/Completed`)

and  `default_downloadDirectory`  for torrents in [Torrent] section..

also not sure what the different is between ` outputDirectory` & `default_downloadDirectory` within the [Torrent] section. (I have both of them  set to `/Users/USER/Downloads/Torrents/Downloads`)

**Comment by clinton-hall** [comment]
watch_dir is only used for a manual run. So no, for automated processing you don't need to set it.

default_download directory affords some protection at the clean-up stage to avoid accidentally deleting other downloads that are in progress.

outputDirectory is where TorrentToMedia moves files to. When set to move/copy/hard-link the script will process the files from the download directory to the output directory so that SC/SR/SB/CP etc can process those files from that location.

I recommend outputDirectory  be set to another location and NOT the same as default_downloadDirectory.

**Comment by XxUnkn0wnxX** [comment]
so with default_downloadDirectory TorrentToMedia will detect the sickchill subdirectory? & then with outputDirectory is used as the staging folder? if so how come NZB doest have a outputDirectory for staging files?


so in theory the way I'm seeing it TorrentToMedia moves DL from Torrents DL Folder to Staging folder
& nzbToSickBeard can also move DL to same Staging folder?

**Comment by clinton-hall** [comment]
Your description is correct. But the "staging" directory is only for torrents.

The reason for this is that nzb downloaders (can) provide separate directories for each download and if every file is fully processed and cleaned up, there is no concern over getting downloads confused.

With Torrents, some clients don't provide the same separations and since a number of people want to keep seeding (for VIP status or good torrent etiquette), this allows us to cleanly process the relevant files without running risk of trying to process a whole directory of seeding files.

With NZBs no-one wants to keep them in download folder and library. With Torrents, many people do want them in both locations, so the staging directory gives us a place to hard/sym-link or copy the files to (note if you are just moving files and not seeding this doesn't matter).
