### ISSUE TITLE
deluge 2.0b2 + NTM = failed to connect to Deluge

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1548]
So I'm seeing TorrentToMedia called, the port is open and listening (webui and deluge-console connect to the same port, even api from my python scripts work) but NTM says failed to connect.

git master latest, OpenSuse Leap 15, py 2.7

In the debug logs, i see the two lines, which confuses me, its making a RPC call but referencing HTTP?
[16:52:38] [DEBUG]::MAIN: Connecting to deluge: http://127.0.0.1:58846
[16:52:38] [ERROR]::MAIN: Failed to connect to Deluge

**Comment by clinton-hall** [comment]
This logging comes directly from nzbToMedia
https://github.com/clinton-hall/nzbToMedia/blob/master/core/utils/torrents.py#L35

We add the http in... this needs to be corrected

Has this ever worked for you (a previous version, or is this a new setup)? I ask since we have done a lot of cleanup, so if an old version worked, this is a bug.

If you wanted to test, edit https://github.com/clinton-hall/nzbToMedia/blob/master/core/utils/torrents.py#L35
to
```
    if client_agent == 'deluge':
        #try:
            logger.debug('Connecting to {0}: http://{1}:{2}'.format(client_agent, core.DELUGEHOST, core.DELUGEPORT))
            tc = DelugeClient()
            tc.connect(host=core.DELUGEHOST, port=core.DELUGEPORT, username=core.DELUGEUSR,
                       password=core.DELUGEPWD)
        #except Exception:
            #logger.error('Failed to connect to Deluge')
```
then do a manual run and see if it fails with a traceback to show what went wrong.

**Comment by mgaulton** [comment]
Sadly, since I switched from uTorrent to Deluge, it has never worked for me.
I even switched to nightly, just on the off chance :) but with that, I also get "no category found in download path" when they are in labeled categories in deluge. :) 
I can live without it but it would streamline things not having to manually intervene for torrent downloads :)

I'll try the test you suggested.

**Comment by mgaulton** [comment]
Ohh, do you explicitly do SSL to the RPC service? I do not use SSL on the deluge side of things as it seemed to break some other things and this is the error below.

[12:09:34] [DEBUG]::MAIN: Connecting to deluge: http://127.0.0.1:58846
Traceback (most recent call last):
  File "./TorrentToMedia.py", line 378, in <module>
    exit(main(sys.argv))
  File "./TorrentToMedia.py", line 294, in main
    core.initialize()
  File "/home/vpnuser/nzbToMedia/core/__init__.py", line 1146, in initialize
    configure_torrent_class()
  File "/home/vpnuser/nzbToMedia/core/__init__.py", line 977, in configure_torrent_class
    TORRENT_CLASS = create_torrent_class(TORRENT_CLIENT_AGENT)
  File "/home/vpnuser/nzbToMedia/core/utils/torrents.py", line 38, in create_torrent_class
    password=core.DELUGE_PASSWORD)
  File "/home/vpnuser/nzbToMedia/libs/custom/synchronousdeluge/client.py", line 146, in connect
    self.transfer.connect((host, port))
  File "/home/vpnuser/nzbToMedia/libs/custom/synchronousdeluge/transfer.py", line 23, in connect
    self.conn = ssl.wrap_socket(self.sock, None, None, False, ssl.CERT_NONE, ssl.PROTOCOL_TLSv1)
  File "/usr/lib64/python2.7/ssl.py", line 951, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 619, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 848, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7f399eb3e6d0>> ignored

**Comment by clinton-hall** [comment]
I include the deluge client from https://github.com/chrippa/gevent-deluge
So I'm not sure exactly how that works (other than to say I had tested it at some point).

**Comment by clinton-hall** [comment]
I my testing I never specifically enabled ssl. I just did as per this: https://github.com/clinton-hall/nzbToMedia/wiki/deluge

**Comment by clinton-hall** [comment]
It does appear from the error you are getting that your system has a very old version of OpenSSL that does expose some vulnerabilities. Perhaps updating that might resolve the issue (and is probably good practice anyway). I'm trying to see if I can reproduce at my end.

**Comment by mgaulton** [comment]
Which is weird because i'm using the OpenSuse packages for it.

**Comment by clinton-hall** [comment]
Are you able to try installing python3 (now supported by nzbToMedia) to see if that works?

**Comment by mgaulton** [comment]
I have python 3.6 installed side by side, I can try that. What changes do I need to make to call it explicitly with py3?

**Comment by clinton-hall** [comment]
These scripts now call `python` so does python link to python2.7 or to python3.6?

You could try editing the first line from TorrentToMedia.py
from `#!/usr/bin/env python`
to `#!/usr/bin/env python3`

If that works, then the issue is cleary with the py2.7 ssl module. Solutions could be to update that module (if available), or to switch the scripts to use Python3... 
To use python 3 permanently (the test above will stop auto updating etc) you can change your default python to point to python3, but that may break other apps/packages etc that are dependent on python2
