### ISSUE TITLE
Invalid subtitles permissions

### ISSUE THREAD

**Issue by ZeGuigui** [clinton-hall/nzbToMedia#1555]
I use sonarr + sabnzbd along with nzbToMedia on a synology nas. I configured it to download en and fr subtitles. Those files are downloaded but the permissions are not set correctly.

The subtitles get "sabnzbd" ownership and rights whereas all the other files get full ACL permissions

Sonarr is configured to take the SRT along with the movie file

**Comment by clinton-hall** [comment]
nzbToMedia calls subliminal to download subs, this creates the sub file.
The issue is the user that runs the script (a daughter process from SABnzbd)  is `sabnzbd`.
I don't know that the script will be able to change the owner of the files created.

If the other files get different ownership, is this something that is specifically set up in sabnzbd?
Does the file-ownership matter specifically, or is it the file permissions that need to change? Can you change the umask that is set for SABnzbd and it's daughter processes?
