### ISSUE TITLE
Adding nzbToMedia to linuxserver/sabnzbd running in docker

### ISSUE THREAD

**Issue by ChuckyNorris** [clinton-hall/nzbToMedia#1558]
Hi

I installed linuxserver/sabnzbd in a docker container (on my Raspberry Pi 3B running LibreELEC) and found that it has no post-processing scripts (it doesn't even have a scripts folder).  Do you know how I can add the sabToMedia script to this set-up?

Thanks
Chuck

**Comment by clinton-hall** [comment]
Depending on the interface into your docker, you would add the script the same as you add scripts on any other system.

I would guess that the easiest way would be to edit the mount points in your docker so that a scripts directory (on your RPi) is mounted inside your docker. You then add and edit your scripts on RPi, and in SABnzbd point the scripts directory to the "mounted" location in your docker.

Other method might be to open a terminal into your docker, then do a git clone on nzbToMedia into your docker (and again configure SABnzbd to point to this location). The main downside to this is that you will likely need to edit the .cfg files via either `vi` or `nano`.

**Comment by ChuckyNorris** [comment]
Thanks for the help. It's set up now but I keep getting a warning from sab during post processing saying:
API key missing, please enter the API key from Config->General into your 3rd party program: 127.0.0.1>python-requests/2.21.0
I have entered the API key into SickChill which is the only program that would be using sab's API. Any idea what the problem is? My router isn't even on ip 127.0.0.1, nor is the SickChill docker container or my raspberry pi...

**Comment by clinton-hall** [comment]
NzbToMedia uses the sab api key to get additional information from sab that isn't part of the parameter set sent during postprocessing.

This extra parameter the script asks for is the "nzoid" which is the download id passed between sickbeard/couchpotato and sabnzbd, so ot helps us confirm which download is being processed.

From memory this is more relevant for CouchPotato.

Take a look autoProcessMedia.cfg
[Nzb]

This is where you enter the sabnzbd details.

**Comment by ChuckyNorris** [comment]
Running ifconfig finds this, I have no idea whst a loopback is :(

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:66084 errors:0 dropped:0 overruns:0 frame:0
          TX packets:66084 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:23145620 (22.0 MiB)  TX bytes:23145620 (22.0 MiB)

**Comment by clinton-hall** [comment]
127.0.0.1 is the ipadress for "localhost". This adress tells the script to look for sabnzbd on the same interface/system.

If you put the sabnzbd api in autoProcessMedia.cfg under[Nzb] all warnings should stop.

**Comment by ChuckyNorris** [comment]
Thanks. I relooked at the .cfg file and found the nzb section. Before I had put the sab api key in the Sickbeard section. All working now :)
