### ISSUE TITLE
Communication between downloader and nzbToMedia over TCP/IP network

### ISSUE THREAD

**Issue by niklashagman** [clinton-hall/nzbToMedia#1616]
It seems like the modern way of creating the perfect PVR system is to run individual pieces inside docker containers. This isolation makes it easy to maintain software and upgrade.
The most common way to communicate between containers is over TCP/IP network. 

I would like to see nzbToMedia running inside a container and downloaders like nzbget or qbittorrent is communicating with nzbToMedia over the network. nzbToMedia is then communicating (as it already does) with software like Sonarr and Radarr over the network.

So the missing part is communication between the downloader and nzbToMedia over TCP/IP network. My question is, how do the developers of nzbToMedia want to see this implemented? It exist so many possibilities.

I can create the docker container and upload it to docker hub. This is a big missing feature in todays PVR setups using docker containers.

**Comment by clinton-hall** [comment]
If nzbToMedia was a running service, I would agree with this. However the script is designed to be run by the downloader (the script must exist in the downloader's docker and when run it becomes a daughter process within that docker).

In order to set up nzbToMedia as a separate docker. The following would need to be true:
 -1a. Downloaders would need to be set to call postprocessing scripts via tcp/ip, or
 -1b. Another script would need to be created, to be run by the downloader, which would call nzbToMedia via tcp/ip, or
 -1c. Downloaders would do nothing after downloading, and nzbToMedia service would need to poll the downloader via api to confirm when downloading is complete, and
 -2. nzbToMedia would need to run as a service with an api (tcp/ip) interface.

with regard to 1c. - This is what CouchPotato and SickRage etc already do by default... the reason this script exists is to try and be more efficient than the regular polling of the downloader.

I appreciate any other information. I am not opposed to this idea, but I myself don't see the benefits at this time.

**Comment by labrys** [comment]
@clinton-hall I have thought about this, but I think its a ways off before it would be feasible.  With the core of nzbToMedia written as a library, you could have an app implemented as a server to serve requests.  The existing nzbToMedia scripts would then be altered to call the API.  

One potential advantage of this type of persistent service would be to securely store root credentials for [handling blueray](#1588) as you could provide them upon launch of the service instead of storing them in the config file.

**Comment by blinkiz** [comment]
May I suggest that the API is created with a ready framework like Hug? https://www.hug.rest/
First simple goal should be to replace what I put into my download client:
x:\path\to\nzbToMedia\TorrentToMedia.py %1 %2 %3
into
http://nzbtomedia.docker/torrenttomedia?param1=%1&param2=%2&param3=%3
The API can then call TorrentToMedia.py with paremeters like %1 %2 %3
