### ISSUE TITLE
QQ: configuration folders

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1676]
I suspect this is a no, from what I've been reading but is there a way to use a command line directive to set a separate folder for .cfg/.db from where the git is pulled?
I prefer to split config from install to make rebuilds easier.

**Comment by clinton-hall** [comment]
it's not a case of this being a "no" but more a case of not being particularly easy to achieve.

At this time nzbToMedia doesn't exist as a service, so we can't start the service (passing in a custom path) and then call it to process each download.
Also, when the script is called, it can receive the parameters via (command line) arguments (as is from SABnzbd, utorrent etc) or from the environment variables (as is from nzbGet and Transmission). so we would need to figure out how to set/pass the directory via these methods when being called.

Having a service is something that is on my want list... but honestly, not sure when that is likely to happen.

it may be possible to achieve what you want by moving the .cfg, .db, and log directory out of the nzbToMedia folder and into another location. Then create a symlink back into nzbToMedia directory so that the scripts can find them.
This way they are still separate and will allow for easier rebuild.
Git should ignore these anyway, so that shouldn't be a problem.

I am quite confident the logs etc will be fine since the script just writes the files into this directory. But I am not 100% sure how writing to the db and the config migraions will be handled. These may still re-save the file back in the nzbToMedia directory and not write to the existing file.... If this is the case, then the solution would be to create hard-links to the other location

So you have the following directory structure

```
~/config
~/config/logs
~/config/nzbtomedia.db
~/config/autoProcessMedia.cfg
~/nzbToMedia
~/nzbToMedia/logs --> Symlink to ~/config/logs
~/nzbToMedia/nzbtomedia.db --> hardlink to ~/config/nzbtomedia.db
~/nzbToMedia/autoProcessMedia.cfg --> hardling to ~/config/autoProcessMedia.cfg
```
If you give this a try, I'd be keen to hear if this works.

**Comment by mgaulton** [comment]
Thanks. I might give this a shot this weekend, if i have time. I'll update you if that happens.
