### ISSUE TITLE
Exiting on Python EOL doesn't account for distro support

### ISSUE THREAD

**Issue by brianjmurrell** [clinton-hall/nzbToMedia#1695]
While:
https://github.com/clinton-hall/nzbToMedia/blob/a320ac5a66428e86702267983b0b03af718228a3/eol.py#L87-L103
is laudible in an effort to educate people about the EOLness of Python, it does not account for [Python 2 being supported by the distros](https://access.redhat.com/solutions/4455511) they are running on beyond the PSF's _official_ EOL date.

You could use something like:

```python
import platform

print platform.linux_distribution()
```

on CentOS 7 for example, which, FWIW, returns:

```
('CentOS Linux', '7.7.1908', 'Core')
```

to create per-distro exceptions and be more complete about the check and resulting action.

**Comment by clinton-hall** [comment]
If anyone wants to create a list of every available distribution and create exceptions, then go for it.

At my side I'm just now trying to determine if I am going to invest anymore time supporting an obsolete language when python3 is easily available.

**Comment by brianjmurrell** [comment]
> If anyone wants to create a list of every available distribution and create exceptions, then go for it.

I don't think any one person needs to create the complete list.  The exception list can be as little the one I provided above for CentOS 7 until somebody else wants to come along and add one.  Don't let the perfect be the enemy of the good.

> At my side I'm just now trying to determine if I am going to invest anymore time supporting an obsolete language when python3 is easily available.

While I can understand your desire not to _try_ (i.e. go out of your way) to continue to support python2, at least as it is currently, nzbToMedia is backward compatible, so why not let it continue to work on distros where it is being supported still?

The problem with older distros like EL7 is that yes, while python3 is available, it's not (and can't be AFAIU) the default (i.e. `#!/usr/bin/env python`) due to the need to continue to support other python2 (as invoked by `#!/usr/bin/env python`) applications that are not yet python3 compatible.

As an alternative, of course I could also change:
https://github.com/clinton-hall/nzbToMedia/blob/a320ac5a66428e86702267983b0b03af718228a3/nzbToMedia.py#L1
in my local copy to specify python3 explicitly but that then becomes a local change in my git source which probably breaks the "auto/self-update" code, doesn't it?

**Comment by clinton-hall** [comment]
yes, making any changes to the shebang will break updating.

sorry if my previous reply seemed `short` I was looking at a number of posts all about python v python3 and there are a number of opinions on these issues.

I have made it such that python2 is still supported in nzbToMedia, just not as a per-distro option. Basically as I see it, I either support python2 or I don't. If it works on python2 there is no reason to support it only on specific distros.

> The problem with older distros like EL7 is that yes, while python3 is available, it's not (and can't be AFAIU) the default (i.e. #!/usr/bin/env python) due to the need to continue to support other python2 (as invoked by #!/usr/bin/env python) applications that are not yet python3 compatible.

By the same logic, these are the applications that should therefore have a shebang that calls `python2` since they don't support `python`.... nzbToMedia currently supports `python` for all "current" versions as well as python2.7

In anycase, if you update to the latest master, python2.7 is supported.
