### ISSUE TITLE
Q - remove unwanted strings from the filename

### ISSUE THREAD

**Issue by fadern** [clinton-hall/nzbToMedia#1706]
Question:
Do you have any support for removing unwanted strings from the filename?
Some indexers add stuff to the original filenames.. like -AsRequested, -xpost, -repost.. These extra strings makes sickchill confused so it uses them as releasegroups...

Star.Wars.The.Clone.Wars.S03E04.1080p.BluRay.x264-CiNEFiLE-AsRequested

**Technical Specs**
1. Download Client SABnbzd
2. Intended Media Management SickChill

**Comment by clinton-hall** [comment]
Are these manual downloads (not snatched by SickChill)?

Generally, if SickChill snatches the episode, it should be able to confirm the release group.

I'm really surprised that SickChill doesn't handle these... I could try and strip them, but I think SickChill should be able to do this better since it would already have an entire naming "library" to identify the relevant parts.

**Comment by fadern** [comment]
Theses downloads are all snatched by SickChill. It would be realy nice if your script could handle this so we/I get more control over this.

**Comment by fadern** [comment]
Solved by https://github.com/clinton-hall/nzbToMedia/issues/1973
