### ISSUE TITLE
File ownership and permissions after Sickchill + Radarr complete running PP scripts 

### ISSUE THREAD

**Issue by sramacha2** [clinton-hall/nzbToMedia#1761]
**Describe the bug**
Not exactly a bug but a question. I have configured SABnzbd version 3.0.0-develop with the 'tv' category and to use nzbToSickBeard.py or nzbToRadarr.py scripts to post-process successful downloads. PVR is Sickchill version  v2020.07.18-1 (master) and Radarr version 0.2.0.1504. Everything works great, except I'd prefer the final files to have ownership as sabnzbd:media instead of sickchill:sickchill or radarr:radarr. Is there a config file that I can make this modification in?

**Technical Specs**
1. Running on Centos 8 kernel 4.18.0-193.14.2.el8_2.x86_64
2. Python version 3.6.8
3. Download Client (NZBget, SABnbzd, Transmission) SABnzbd
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) SickChill + Radarr

**Expected behavior**
Downloaded files after post-processing are set to sabnzbd:media ownership and group rather than sickchill:sickhill or radarr:radarr

**Log**
Since there are errors or failures, not sure if logs are needed, but be happy to provide upon request :+1: 

Thank you in advance! Love the PP scripts in the nzbToMedia folder!!

-SR

**Comment by sramacha2** [comment]
So sorry, I meant to say "Since there are _NO_ errors!!

**Comment by sramacha2** [comment]
Also wondering if nzbToMedia scripts have been tested with SABnzbd v3.0.0-develop?

**Comment by clinton-hall** [comment]
I have not specifically tested with SABnzbd v3.0.0-develop. Appreciate any feedback.

As far as ownership goes, it may depend on how you have the processing set up... If you set SickChill and Radarr to MOVE files, the file ownerships should still be sabnzbd... but if you set these to copy, then the new copies will be owned by sikchill and radarr. Also, any new folders created etc would be owned by sickchill/radarr.

**Comment by sramacha2** [comment]
In Sickchill, Post Processing is disabled because I have the SABnzbd 'tv' category script set to nzbToSickBeard.py. The Post Processing tab in Sickchill is the only place to either 'Copy' or 'Move' files but PP has to be enabled for that. Not sure what other setting is available to move the files.
Same in Radarr, I have the 'movie' category to use the nzbToRadarr.py script to do the PP and I don't see a setting in Radarr to move instead of copy the file.

I have been testing the nzbToMedia scripts against SABnzbd v3.0.0-develop, I'd be happy to help you with anything to get them fully tested against this version. As a matter of fact, I'll be opening a new issue that I see already with SABnzbd. For some reason SABnzbd is leaving the original movie folder in the Folder/Path set in the 'movie' category. Strangely, this issue doesn't happen when SABnzbd runs the nzbToSickBeard.py script for the 'tv' category.

**Comment by clinton-hall** [comment]
The way nzbToMedia works is that is does some checks, and then passes the files to SickChill/Radarr to be processed.
Aside from some renaming of obfuscated files, etc, nzbToMedia does not do the renaming.

So Renaming is done by SickChill/Radarr and the renaming methods are defined in those configs.
What is disables is the Automatic checks (browsing completed download directory, and "asking" sab the status of the download. Instead the downloader triggers the script which in turn tells SickChill/Radarr that the files are ready.

Since the script is run by SABnzbd, the sabnzbd is the owner of any file created by nzbToMedia. If the owner is showing as .e.g "sickchill" that confirms that the sickchill user (the scikchill app) is responsible for creating (or modifying ownership of) that file.

In SickChill, under postprocessing, enable should be unchecked (to disable AUTOMATIC) processing, but you should still define the processing method, episode naming, and metadata etc.

In Radarr, the config should be under "Complete Download Handling"
https://github.com/clinton-hall/nzbToMedia/wiki/radarr

For the movie folder staying and the tv folder being removed. The difference here is not SABnzbd, but rather the way Raddar is handling this vs SickChill. (i.e. SickChill appears to be cleaning up the episode folder, Radarr is not.

I believe if you set
autoProcessMadia.cfg
```
[General]
    force_clean = 1
```
this should clean up the leftover directory.

**Comment by sramacha2** [comment]
The settings you recommend in both SickChill and Radarr were all set including the 'force_clean = 1' in autoProcessMedia.cfg file. I double checked Radarr and CDH is enabled as well as 'Remove' button enabled for both CDH and FDH. So I'm not sure why the movie files are being left behind? Do you think I might still be missing a setting in Radarr that's causing this?
One thing I'd like to inform is regarding the 'force_clean' flag. This flag was doing its job perfectly before I switched to SABnzbd v3.0.0-develop. It was cleaning and there were no leftover files after a successful download. Even now it seems to do it's job for tv shows except for movies. Unfortunately, I didn't note down the version I was using before the switch but I believe I installed it using 'git checkout master' as opposed to 'git clone' of SABnzbd3. I'm a git novice so I don't know if that makes a difference in versions. The reason I switched is due to python3 because the previous version of SABnzbd wouldn't start with python2.7 because of a lot of missing python modules.

If you need debug logs I'd be happy to provide them to you, if that helps.

I really appreciate your help and time on this :-)

**Comment by sramacha2** [comment]
Crap, after I posted my reply to you I went back and checked to see if 'Rename' was enabled in Radarr. It wasn't, so I enabled it and I'm trying a new download. Will post the results as soon as the download is completed.
Sorry about that!

**Comment by sramacha2** [comment]
So I manage to set the file ownership and permissions correctly for the files that SABnzbd downloads. I had to set permissions to 664 in SABnzbd and more importantly turned the SGID flag on for the directory where SABnzbd was downloading files to. This allowed SickChill and Radarr to PP the files without any issues.
As of now, it seems the nzbToMedia scripts are working as designed and would like to thank you for all your time and effort on this.
Again, my offer to help you test the scripts with v3.0.0-develop of SABnzbd still stands. Let me know what if any I can do in this regard.
I'll leave it up to you to close this issue or I can close it also :+1: 

-SR

**Comment by clinton-hall** [comment]
Ok... glad to hear you got it all working.
as far as testing scripts with v3.0.0-develop of SABnzbd, sounds like the scripts are called and are working correctly. So that looks promising.

Please let me know if you find any further issues.
