### ISSUE TITLE
Getting some warnings (python 2.7 is no longer supported)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [clinton-hall/nzbToMedia#1799]
**Describe the bug**
running nightly build: d4d5f00a188c19732284305cff648b95ca0a7859
getting some warnings about python2, python2 located in /usr/bin (handled by the system cannot remove)

**Technical Specs**
1. Running on macOS 11.0.1
2. Python version Python 3.8.6
3. Download Client: Sabnzb
4. Intended Media Management: Medusa

**Log**
`/Users/USER/Apps/nzbToMedia/eol.py:148: LifetimeWarning: Python 2.7 is no longer supported.
warnings.warn(msg, LifetimeWarning)`

2020-12-07 21:05:02 WARNING ::MAIN: Failed to locate 7zip. Transcoding of disk images and extraction of .7z files will not be possible!
2020-12-07 21:05:02 WARNING ::MAIN: Failed to locate par2. Repair and rename using par files will not be possible!

![Screen Shot 2020-12-07 at 9 21 23 pm](https://user-images.githubusercontent.com/2242880/101339333-62fd7f00-38d2-11eb-9ff0-055d29deee8a.jpg)
@clinton-hall 
I have 7zip & par2 installed via brew & python3 is main, so not sure why I'm still getting these warnings.

inside sab Full Log at run: https://gist.github.com/XxUnkn0wnxX/33f6babdc2efa859d3ad88beed7468d2

since apple controls /usr/bin (due to SIP, nothing can be edited in /usr/bin), can the warnings regarding python2 be suppressed if nzbtomedia is running on a mac since its a tad annoying.

**Comment by clinton-hall** [comment]
I believe this is due to SAB (older version) always using python2.7.
Newer version of SAB will use the system default (Python3) which would stop the first warning.

Where are your 7zip and par2 binaries installed? these should be found if they are on the PATH exposed to the script (the PATH that exists for SABnzbd). 

If it is the case that the script is finding /usr/bin/python over /usr/local/bin/python then this can be fixed by editing the PATH variable in the init (or whatever the launch script is for SABnzbd itself)

just add
```
export PATH = /usr/bin/local:$PATH
```
before the script actually starts SABnzbd.

Likewise, you can also add the path for 7zip and par2 in the same place... or symlink them into /usr/local/bin if they aren't already there.

**Comment by XxUnkn0wnxX** [comment]
i'm running sab 3.1.1 [99b5a00]

& sab runs `nzbToSickBeard.py` directly

**Comment by XxUnkn0wnxX** [comment]
ok all good, it seems my env variables were thrown off after big sur update...

**Comment by clinton-hall** [comment]
Glad you got it sorted.
The hard part for me is that I don't know OSX at all...
