### ISSUE TITLE
Plex : no token refresh

### ISSUE THREAD

**Issue by nixxou** [clinton-hall/nzbToMedia#1875]
I noticed that after a while, the script don't update plex library anymore.
I could be wrong, but i think it's due to the fact that now, Plex token do not have an infinite lifespan.
Most of the app doing plex notification ask for login/pass on top on the plex token to refresh it.

See here : 
https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

`Tip!: The method explained in this article will get you a token that is valid temporarily. If you’re working on a tool or app that needs more permanent authentication, please instead use the [method outlined](https://forums.plex.tv/t/authenticating-with-plex/609370) in our third-party development forum.`

**Comment by clinton-hall** [comment]
That page hasn't been updated since 1 July 2020. 
I have had a look at the original beets/plex updater and it doesn't look like this has changed in the last 3 years other than to include https and a few (non functional) formatting changes.

So I am not convinced that this has changed significantly. Have you followed the guidance in that article to create a new token?
