### ISSUE TITLE
QQ:require_lan

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1885]
What is the correct usage of the below in my config.
I want to keep anything that is english, or japanese (for anime) and eliminate the rest.

 # Required media audio language for media to be deemed valid. Leave blank to disregard media audio language check.
    require_lan =

**Comment by clinton-hall** [comment]
I have added multiple require_lan in a new fork.
Can you please test this in `req_lan1` fork?
Set the config `require_lan = eng,jpn`

This should ensure that each media has either English or Japanese audio.

As per previous post. If you want the `or Japanese` to apply to Anime only, then you would need to set up a second instance of the script as currently the required language is global and not Category specific.

**Comment by mgaulton** [comment]
Got it, I'll check this out. Sorry, been busy enough I didn't get back to this sooner.

**Comment by mgaulton** [comment]
I've run an english and an anime through, no issues that i've seen.
Trying something german and korean next.

**Comment by mgaulton** [comment]
And German worked.
How will this handle media with no defined language name?

**Comment by clinton-hall** [comment]
How will this handle media with no defined language name?
- It will mark this as failed due to missing required language"

`valid_audio = [item for item in audio_streams if 'tags' in item and 'language' in item['tags'] and item['tags']['language'] in require_lan ]`

So, if there is no match between the audio stream languages, and required languages, then the script will mark this as "failed due to missing required language"

If there are no ['tags']['language'] defined, or no ['tags'] at all, then this will also be flagged as "failed due to missing required language"

If these tags don't exist (and for most decent media I have seen then do.... ) then I would have to assume the audio name would have to exist in the download title, the filename, or the nfo.... But I haven't looked to parse those for confirmation as I believe the language tags are much more accurate and available for most media.

If there are no audio_streams at all then this is marked as "FAILED: Video_Name name has 1 video streams and 0 audio streams"
Which should only be an issue if you were actually downloading an old "silent" movie that didn't have any audio streams (again, I haven't come across any of these as I believe these actually have music played anyway)

**Comment by clinton-hall** [comment]
All merged in Master now
