### ISSUE TITLE
::MAIN: Category:[tv] is not unique, ['SickBeard', 'NzbDrone'] are using it.

### ISSUE THREAD

**Issue by rogueosb** [clinton-hall/nzbToMedia#412]
I'm using NzbDrone to organize my tv shows, and when using the new NzbDrone option (via nzbToMedia.py), it gives me the following error:

::MAIN: Script triggered from NZBGet Version 13.0-testing-r1028.
::MAIN: Category:[tv] is not unique, ['SickBeard', 'NzbDrone'] are using it. Please rename it or disable all other sections using the same category name in your autoProcessMedia.cfg and try again.

However, I set the SickBeard category to disabled in the .cfg file, and upon every post-process it re-enables itself (enabled = 1). I also tried setting the SB category name to something else (e.g. "disabled") in NzbGet, but it still does not work. When using the nzbToNzbDrone.py it works fine, as I'm assuming it forces the correct type.

I'd prefer to use the main script for all my categories, but at least it works on the NzbDrone script for now.

EDIT: I wonder if adding an NzbGet option to enable/disable either sickbeard and/or nzbdrone could help fix this (to prevent enabled = 1 being auto-set)?

**Comment by breezytm** [comment]
That's just weird. I spent like two hours trying to figure this thing out but couldn't understand why the program would care if I set nzbdrone as tv and SB as tv. I am moving away from one and trying use the other. Both software do pretty much the same thing but turns out it cares. The whole time I thought I did something wrong until I read the config file and realized it is looking for tv2 as a category. Now that I set it up as tv2 it ran successfully. Do you log that information in as an error for a reason?

**Comment by clinton-hall** [comment]
The reasoning here is that everything is based on the category. So when the script sees the category as tv it needs to know where to send the files. If there are 2 different apps set to use this category, it doesn't know which is correct so it logs the error and exits.

**Comment by breezytm** [comment]
Yeah I went through the code and figured it out but at the time it just didn't make any sense to me. Is it something that you plan on leveraging in the future for users like myself who didn't know don't end up spend precious time trying to figure out the obvious thinking it can't be? :)

Maybe enable and disable. I mean I can't imagine anyone using both at once.

Again if it's not worth your time don't worry about it. I landed on this bug post here while checking my sanity. I am most certain glad that I wasn't the only one lol

**Comment by clinton-hall** [comment]
I thought this did only cause an issue if they were enabled for both SickBeard and nzbDrone. So enable/disable should work? Or are you saying this error came up even when one was disabled?

**Comment by breezytm** [comment]
Yeah it does it for me doesn't matter what I do. The weird thing is I used NZBGet with SB for a while and never had that issue until i decided to use Sonarr. 

Things i've tried so far:
1. Set tv for sickbeard as a category
2. Set tv2 for sonarr as a category

Doesn't work. 

1. Set sickbeard to enable = 0 

Doesn't work. 

Clear all SB related filed and also delete sickbeard category in NZBGet not the cfg file.  

When I did that it starts complaining about tv2. It says it's being share by both which is not true. If i reverse the change it starts complaining about tv.

Can you add the disable/enable feature in the GUI rather than having to go to the cfg file to do it.

**Comment by breezytm** [comment]
May you should pre-configure the categories. That way you'll know for sure they will always be unique instead of monitoring whether it is unique or not.

**Comment by clinton-hall** [comment]
Pre-defining categories upsets people. Particularly where the category creates a directory...

Can you show the full log for a sonarr run that has this error?

**Comment by breezytm** [comment]
Yeah i figured that's probably why you diidn't do it. 

I changed everything back to what they were when sickbeard was working. SB is set as category "tv". I deleted sonarr category and did it again. This time I used a new word just to see what happened. Instead of "tv2" as category, I did "episodes". I also deleted the "tv" and "tv2" dir from /nzbget/dst/ and created "episodes" dir for tv downloads. I downloaded two shows to test and they both post-processed successfully. 

I don't know what fixed the issue. Whether setting "episodes" for sonarr as a category instead of "tv2" or deleting "tv" and "tv2" folder. But I would say this. Before sonarr, I only had a "tv" folder and a "tv" category for sickbeard . And now I only have "eposides" folder which is created for sonarr. Could it really be the download folder?

**Comment by clinton-hall** [comment]
This particular issue shouldn't have come from the download folder.... But I wouldn't rule it out without some extensive testing. The Torrent section of the code does use the directory to determine category, so there may be some cross-over in there (but with a defined category this really shouldn't happen)

**Comment by breezytm** [comment]
Yeah i wish i could test this further but things are working so great right now I don't feel like mesing with it. If anyone reports that issue again, just have them delete the folder and see what happens. 

Thanks for the help. Much appreciate it.
