### ISSUE TITLE
corruption check

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#534]
I've noticed with Movie downloads that occasionally i will get one that won't render. I'm not sure if this is bypassing the corruption check (utorrent download, not passed for some reason) or not.

Wondering if there is a way to manually call the corruption check against a folder to recheck the files in it, so I can mark and delete those ones.

**Comment by mgaulton** [comment]
Any chance there's an updated version of the code you shared with me here? I looked at the history here and you referenced nzbget failurelink.py, would that be something i can use/

**Comment by mgaulton** [comment]
Scratch that, i found it and made the mods you did. Thank you.

**Comment by mgaulton** [comment]
I've been using this mod for ages but noticed running it on a drive, it had more corrupt than I thought. Would more modern codecs lead to this?
I'm building a list of files to manually verify, but wondering if you had a clear trick to confirm this?

**Comment by clinton-hall** [comment]
As far as modern codecs, I would suggest upgrading ffmpeg/ffprobe. The latest version of these should have all codec /package types.

Otherwise, the general process that the scripts use to verify a valid audio and video channel shouldn't have changed much.
(unless newer ffprobe has changed the output formats etc... )
