### ISSUE TITLE
Prefer stream copy over no_copy flags for video streams if codec is allowed

### ISSUE THREAD

**Issue by mjonuschat** [clinton-hall/nzbToMedia#662]
Given I have a MKV with a H.264 video stream and AC3 audio stream, VCODEC set to 'libx264', VCODEC_ALLOW to 'h264', VPRESET is 'slow' and VCRF set to 21,

Currently this results in the video stream being recoded all the time. It would be nice to have a way to tell the transcoder that it's OK to copy the stream.

Something along the lines of a VCODEC_PREFER_COPY option (or making the no_copy trigger flags configurable)

**Comment by clinton-hall** [comment]
if the VCODEC is in the VCODEC_ALLOW list (you can add several codes to this) then it will stream copy unless your other values (VCRF) mean the existing Stream is outside of the requirements.

**Comment by yabawock** [comment]
Yeah, it currently switches to "copy" mode in https://github.com/clinton-hall/nzbToMedia/blob/master/nzbtomedia/transcoder/transcoder.py#L212 and then copying gets overridden due to having specified VCRF and VPRESET in https://github.com/clinton-hall/nzbToMedia/blob/master/nzbtomedia/transcoder/transcoder.py#L236

So basically I am looking for a configuration switch to disable the no_copy check.

**Comment by clinton-hall** [comment]
Ok... I'll see what I can do...
