### ISSUE TITLE
Userscript - Run in addition to CP/SB update

### ISSUE THREAD

**Issue by clinton-hall** [clinton-hall/nzbToMedia#664]
Some users would like this to run userscript as well as autoProcessTv/autoProcessMovie etc...

This might become interesting for config parsing, since this will create 2 sections that match?
Would also need an option to run Before/After renaming?

**Comment by kooimens** [comment]
This can be useful for Headphones as well. I use headphones to search for music and send them to sab. With the nzbtoheaphones script the music is moved to a certain directory. But only moved, not tagged, because a seperate beets installation and configuration is handeling my tags a lot better and I got much more options to set. Beets runs at command line so it would be perfect to run a .sh script after nzbtoheadphones is a success. The .sh scripts would be timething like ```beet import headphones/moved/directory/```
