### ISSUE TITLE
AttributeError: 'module' object has no attribute 'main'

### ISSUE THREAD

**Issue by brando56894** [clinton-hall/nzbToMedia#670]
nzbToSickbeard crashes immediately upon execution with this error. See here for more details: https://sickrage.tv/forums/forum/help-support/nzbtomedia-support/16712-attributeerror-module-object-has-no-attribute-main

**Comment by clinton-hall** [comment]
Make sure that in the nzbToMedia directory, the user that runs SABnzbd has full read and execute permissions for all nzbToMedia files... 
It appears here that nzbToSickBeard.py is not able to correctly find and load nzbToMedia.py

Otherwise try a re-clone of nzbToMedia.py, it could be that some of these files have become corrupt?
