### ISSUE TITLE
Error message when IP address contains a zero

### ISSUE THREAD

**Issue by kazooless** [clinton-hall/nzbToMedia#696]
I am using FreeNAS and installed your script to run with sabnzbd & sickbeard. FreeNAS puts each plugin within its own jail, so sickbeard has a different IP address than sabnzbd. I received this error message when running:

File "/var/db/sabnzbd/autoProcessTV/nzbToSickBeard.py", line 47
    sbhost=192.168.0.22
                   ^
SyntaxError: invalid syntax

The carat above is actually under the zero

**Comment by clinton-hall** [comment]
nothing to do with `0`

The problem is that you have uncommented a line that is not code.. it is a descripter to allow use with NZBGet web ui.

You should not edit `/var/db/sabnzbd/autoProcessTV/nzbToSickBeard.py`

Instead you should set all options (as required) in `/var/db/sabnzbd/autoProcessTV/autoProcessMedia.cfg`

please see the wiki https://github.com/clinton-hall/nzbToMedia/wiki
