### ISSUE TITLE
Concat for CD1 CD2 + transcoding for ISO VOB TS. HowTo ? (old #570 closed now)

### ISSUE THREAD

**Issue by thesatman** [clinton-hall/nzbToMedia#792]
Hi Clinton. Please allow me to ask a few questions on this subject. I never really managed to use this as intented. Back in November 2014 when you closed this topic, I entered a last question, asking how you finally programmed the entire transcode section. But I never got an answer, and I kind of forgot about it...

How is this now intended to work, how do I set up my config file? Not sure if you went for solution 1, 2 or 3... Let's assume that what I want is following:

1) ISO VOB and video_TS needs to be transcoded to one big file in mkv
2) cd1 and cd2 cdxx files need to be glued together to one file.

**Comment by clinton-hall** [comment]
Sorry for not responding. I saw your question, but never had time to look into it, and kept forgetting to come back to it. I haven't had a lot of online time.

So I didn't use option 2 (that is still another open enhancement to allow different transcoding options for different input qualities/codecs/types).

So the main features you want "should" be quite straight forward.

First, set the option `concat = 1`
this will combine the cd1, cd2 etc.
then just set your preferred output profile (or set all of your codec info etc in the custom profile)
The transcoding of iso/VOB should all be handled without any other settings.

**Comment by clinton-hall** [comment]
check out https://github.com/clinton-hall/nzbToMedia/wiki/Transcoder
this details the options for iso/vob etc. Set as per the example there, then remove some of the "ignore_extensions" as appropriate to also allow concat/transcode of other files.

To try and improve concat only (i.e join multiple avi files without demuxing them all) you can create a custom profile that allows multiple codecs etc, so that the streams are just copied... however this is more work, it may be easier to just join and transcode to your preferred format (mkv or mp4 with x264 codecs)

**Comment by thesatman** [comment]
You say "then remove some of the "ignore_extensions" as appropriate to also allow concat/transcode of other files"

	That is just it what I think is what I keep stumbling over. The way I understand it, in the transcoder section, by putting concat = 1 and transcode = 1, it will indeed join files cd1+cd2 and transcode them to the default output file type of preference. But it will as well transcode f.ex. an avi file, even it it is a decent sized one. Not only sio and vob or TS files. Or am I wrong here?
