### ISSUE TITLE
sabnzbd - categories : what script to use?

### ISSUE THREAD

**Issue by thesatman** [clinton-hall/nzbToMedia#858]
My current setup in sabnzbd/categories:

film: nzbToCouchPotato.py
music: nzbToMedia.py
tv: nzbTosickbeard.py

What is the difference between this 3 scripts? Should I be using nzbToMedia.py on all categories?

Lately I noticed that SickRage passes the TV show download on to sabnzbd. The download is completed and the file is renamed correctly and moved to the correct folder (destination folder for tv/show/season_xx/). But Plex TV library is not being updated anymore.

Can this have something to do with using the wrong script mentioned above? What is the routine? Does sabnzbd after completion of the script above update Plex directly, or does the script warn Sickrage to run an update?

**Comment by clinton-hall** [comment]
you can use nzbToMedia.py for all categories, or you can have each category call nzbToXXXX.py as wanted... I call nzbToXXXXX simply because it adds another level to help ensure TV and Movies are separated...

Anyway, the script tells SickRage to do the process (after doing some other checks/transcoding etc as wanted). It also can do the plex update, or SickRage can be set to do the plex update.
