### ISSUE TITLE
Failing Post-process to SickRage

### ISSUE THREAD

**Issue by Zumbug** [clinton-hall/nzbToMedia#903]
Hi all,

I am having difficulty getting NZBGet to post-process to SickRage using nzbToMedia.

Post processing fails with the following error:
 
> ERROR   ::MAIN: A problem was reported in the /volume1/video/nzbGet/scripts/nzbToMedia/nzbToSickBeard.py script. 

I am running everything on a Synology DS213, sickrage is on the latest version, nzbToMedia is on autoupdate.

Where can I get a more detailed log on what is failing?

Full log is here: http://pastebin.com/8MVHK0Yn 
Config is here: http://pastebin.com/PF4vQb64 

Thanks for the help, let me know if you need more information.

**Comment by Inervo** [comment]
Hi,

I'm having the same issue since yesterday, no idea why.

Thanks for the help.

**Comment by displaced** [comment]
Exactly the same for me, too.

SR Version:  BRANCH: (master) / COMMIT: (92b6eb03ee75db853e3fecb3367ce12d56a09abe)
...and the latest nzbToMedia.

**Comment by chrisanthropic** [comment]
Same here on a DS413.

**Comment by displaced** [comment]
Hmm.  There appears to be some sort of shenanigans going on in the SickRage team.  An argument happened and now there's SickRage and SickRageTV existing as two separate projects (where 'SickRageTV' is the older one).  

I just switched to the 'new' project and post-processing is once again working.  I've read about all the politics behind the scenes of the split and it's rather sad.  I'd really prefer that the new project stopped using the 'SickRage' name, so using this leaves a bit of a bad taste in my mouth...

**Comment by Zumbug** [comment]
Thanks for the reply!

So based on this, and your knowledge, should we be using SickRage or SickRageTV?

**Comment by chrisanthropic** [comment]
Yeah, updating to the 'new' / split off SickRage fork fixes PP for me.

@Zumbug - as for what you should be doing, it's up to you. The short of it is this - The creator/maintainer of SickRage didn't like some of the actions/decisions of a developer and kicked him out. The rest of the team followed and left the creator/maintainer as the sole coder for SickRageTV. The rest of the team is now working on SickRage. His version is no longer working for me, theirs is. That's my take on it.

Regardless, this seems more of a SickRageTV bug than an NZBtoMedia issue.

**Comment by labrys** [comment]
@chrisanthropic not that its particularly relevant to the conversation but he kicked the rest of the devs too, as well as blocking them from the IRC channel and deleting some of their accounts on the old forum.

@displaced As for the naming, we have been looking to rename SR since well before the split, as was discussed in the old repo's issue tracker which is currently offline.  If you have any suggestions for a new name please let us know [here](https://github.com/SickRage/sickrage-issues/issues/26) we would be glad to get the input.

@Zumbug Obviously as a dev for SickRage, I am not unbiased, but we actively support and maintain SickRage while the old repository gets little attention and has the issue tracker closed at various times, etc.  If you do decide to switch, let us know if you need any assistance.

FEATURE REQUESTS use [Feathub](http://feathub.com/SickRage/SickRage)
BASIC QUESTIONS try our [IRC channel](https://kiwiirc.com/client/irc.freenode.net/?theme=basic#sickrage-issues)
OTHER ISSUES go to our [issue tracker](https://github.com/SickRage/sickrage-issues)

**Comment by bservet** [comment]
I also migrated to the 'new' Sickrage fork to get PP working again but I'm getting the error "No processable items found in folder".

Any ideas why it's not working? The paths and permissions seem to be ok.

**Comment by labrys** [comment]
@bservet If you're on the new SR that's not a error its a debug statement meaning there is nothing there that needs to be processed.   If there is something that you think needs to be processed, make sure the show is added to SR first.  If you still have issues, please enable debug logs and posts on our issue tracker.

FEATURE REQUESTS use [Feathub](http://feathub.com/SickRage/SickRage)
BASIC QUESTIONS try our [IRC channel](https://kiwiirc.com/client/irc.freenode.net/?theme=basic#sickrage-issues)
OTHER ISSUES go to our [issue tracker](https://github.com/SickRage/sickrage-issues)

**Comment by bservet** [comment]
@labrys Thanks! That fixed the problem. 

It wasn't clear to me that the error actually meant that the show itself wasn't detected as something for which SR wasn't configured to process.

**Comment by labrys** [comment]
@bservet Glad to hear. :+1:  If you could please post future SR issues on our issue tracker to help other SR users find them and I'm sure nzbToMedia would also like to keep their issue tracker on topic.

**Comment by Zumbug** [comment]
@labrys To confirm, I am all setup and working now, on your guys repo now and everything is all good.  Thank you for the help and support, and keep up the great work!
