### ISSUE TITLE
Post-process-script nzbToMedia/nzbToSickBeard.py failed

### ISSUE THREAD

**Issue by davy55** [clinton-hall/nzbToMedia#906]
Since a couple of day NZBget gives this error:
Post-process-script nzbToMedia/nzbToSickBeard.py failed

the only error in the logs I found was this:
nzbToSickBeard: [06:07:12] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!

How do I fix this?

**Comment by gilly65** [comment]
Using SickRage and NZBget I'm getting the same thing. I ran it over SSH and it still failed.
Pastebin log when I ran it manually over SSH using putty

http://pastebin.com/vY5md41w

hopefully that helps you out...

**Comment by alexandrezia** [comment]
Same here, if I revert SickRage to commit: d294e9faf48d45051a50d4e2cf3a0252c28d5b17
than it works.

**Comment by alexandrezia** [comment]
Just found out, using nzbToMedia  nightly  branch, it is already fixed.

**Comment by firatuzman** [comment]
I have SiCKRAGETV commit:4da36fb1c4fde840cb5ddae0da65fdb56a31c2d0
Same here. torrent downloader fails to notify sickrage after a download is completed since few days
If the nightly branch is fixed when will it be merged?
Thanks

**Comment by noharm1010** [comment]
same error here:

INFO    2015-12-09 22:12:31     nzbToSickBeard: [22:12:31] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
NFO    2015-12-09 22:12:33     nzbToSickBeard: [22:12:33] [ERROR]::MAIN: A problem was reported in the /usr/local/nzbget/share/nzbget/scripts/nzbToMedia/nzbToSickBeard.py script.
WARNING 2015-12-09 22:12:33     Marking Family.Guy.S14E05.HDTV.x264-FLEET as bad
INFO    2015-12-09 22:12:33     nzbToSickBeard: SickBeard: Failed to post-process. SickBeard does not support failed downloads!
ERROR   2015-12-09 22:12:33     Post-process-script nzbToMedia/nzbToSickBeard.py for Family.Guy.S14E05.HDTV.x264-FLEET failed


Any solutions to fix it?

**Comment by os49808n** [comment]
In NZBTOMEDIA / NZBTOSICKBEARD configuration in NZBGet change sbfork to sickrage from auto. That fixed it for me.

**Comment by gilly65** [comment]
mine was already at auto...

**Comment by wisie** [comment]
Same issue as the previous poster. This has been bothering me for a few weeks and hoping someone might have a solution.

**Comment by clinton-hall** [comment]
leave sbfork as auto... but try switching to nightly branch...

actually... I'll merge nightly up to master so that this should be resolved...

**Comment by davy55** [comment]
I thought I was the only one with this problem.
Thanks Clinton-Hall, how long will it be before the merge is complete?

**Comment by clinton-hall** [comment]
merged now... try updating and test...

**Comment by davy55** [comment]
maybe a stupid question, but how do I update?

**Comment by firatuzman** [comment]
Will have a look at it tonight. My procedure:
1-backup autoProcessMedia.cfg
2-git pull (from terminal in nzbtomedia directory, assuming you used git in the first place)
3-put back autoProcessMedia.cfg (add resume = 1 parameter under [torrent] just under chmodDirecotry = 0, which is a new parameter with v10.13)
4-see if it works now (snatch a small sized episode in sickrage)

**Comment by davy55** [comment]
when i do a git pull it gives an error = git not found

**Comment by firatuzman** [comment]
do you remember how you got nzbtomedia? It seems like you dont have git at all. You may just manually download the nzbtomedia zip and unzip it. Dont forget to backup autoProcessMedia.cfg or with CAUTION do
0- backup config
1- sudo apt-get update
2- sudo apt-get install git
2- try git pull if fails
3- go to directory containing nzbtomedia (hope not in sickrage or similar)
4- delete nzbtomedia folder or maybe you dont need to, i dont know :)
5- git clone git://github.com/clinton-hall/nzbToMedia.git (dont do this inside nzbtomedia folder but in the directory one level up)
6- put back config
7- pray your system doesnt burn :)

**Comment by davy55** [comment]
nzbtomedia was installed with nzbget, I didn't download it separately. point 2 gave sudo not found error
and point 7 has me a bit worried :|

**Comment by firatuzman** [comment]
Your installation method differs i think you should reach nzbget and ask them to merge this update. Is nzbget updated frequently and does your system autoupdate nzbget?

**Comment by davy55** [comment]
will do that, nzbget isn't updated frequently and my system (nas/synology) doesn't autoupdate nzbget.
there is no possible way to update nzbtomedia on my system?

**Comment by gilly65** [comment]
nzbtomedia was installed with nzbget here too. however when it runs it should auto update (when it's called by nzbget) at least mine updated automagically for me.

**Comment by davy55** [comment]
how do you know that it has been updated? if i check my version, it still is the one from september

**Comment by clinton-hall** [comment]
@davy55
Syno must have included nzbToMedia with NZBGet but without git.
@gilly65 must have a different system (QNAP or ASUSTOR) where nzbToMedia is installed with NZBGet using git...

What you will need to do is install git package from syno community. Then log in to your nas via ssh and cd into the scripts directory...

    mv nzbToMedia nzbToMediaold
    git clone http://github.com/clinton-hall/nzbToMedia.git .
    cp nzbToMediaold/autoProcessMedia.cfg nzbToMedia

And then you should have everything up to date and working... If so, you can delete nzbToMediaold from the scripts directory.

If you can't install git, follow the same process, but instead of git clone, just download the latest version as zip and extract to the nzbToMedia folder.

**Comment by gilly65** [comment]
QNAP, although it updated it's still failing.
I may have deeper issues here :/

**Comment by wisie** [comment]
Running a QNAP here too. Mine seemed to have resolved itself over night?

Thanks for all your support on this Clinton. Appreciate your dedication :)

**Comment by davy55** [comment]
IT WORKED! thank you Clinton, really appreciate the help!

**Comment by firatuzman** [comment]
Just had the chance to check. It has updated automatically and IT WORKS! Thank you @clinton-hall

**Comment by firatuzman** [comment]
@gilly65 Check your autoProcessMedia.cfg settings

**Comment by WaterflyNL** [comment]
my solution: 

Summery. :

1) Go into Sickrage and make a backup.
2) Go to the Synology Package Center and remove Sickrage.
3) Then Reinstall Sickrage, but now in the installation screen/wizard add the new URL.
git://github.com/SiCKRAGE/SickRage.git
4) Restore your backup, and restart Sickrage.

**Comment by firatuzman** [comment]
You should also check https://github.com/SiCKRAGETV/SickRage.git
This is the original sickrage repository (echel0n maintains this version). It has a warning for the repository you gave (miigotu maintains your version who has split up to form the new sickrage).
I am not sure who to believe, but check my link and the warning. @clinton-hall may comment on this.

**Comment by clinton-hall** [comment]
At the end of the day open source does hold some degree of risk to users.

In theory, I could push some code that would recursively start deleting all of your data... but clearly I have no interest in doing this.

Nor do I really believe echel0n or miigotu would do something malicious... they have clearly had a difference of opinion over the future of SickRage. I believe echel0n's comment was directed more to the fact that some users were being automatically switched over (or encouraged over) to the other fork without the user knowing what was happening...

The thing to remember is there are people who follow these repositories and comment on commits. Anyone seeing anything malicious would (and indeed should) report this on the repository and to github. 

For the record, within minutes of pushing a commit that could (in very specific conditions) delete a download, this was flagged on here by a user, and I acted as quickly as possible to correct. Let me also say this was an error and was not intentional.

There are other ways of protecting against such possibilities. You can run your App (e.g. SickRage) as a restricted user (not admin or root) and this would prevent the App from being able to delete or modify system files or any files it is not specifically given permissions to.
You can also run your App in a "Jail" or chroot etc.

As to the 2 repositories. I am trying not to choose sides on this one.
echel0n did a LOT of work on this repository and showed me how to greatly improve the flow and layout of this repo. I consider echel0n a friend and respect his opinion.
miigotu is one of the key guys who helped maintain SickRage while echel0n was away (I believe he had family concerns that rightly took priority). 

For the various Apps I maintain, I am looking to have a method of providing the user the right to choose the repository. I intend to let the users decide.

Trust that if I were to find or be informed of any malicious code on any repository relating to the project (SickRage, HeadPhones, CouchPotato, SickBeard, Mylar, Gamez, NZBGet, SabNZBD etc) I would definitely host a warning/discussion here (as an independent to all of these repos). Likewise, if anything went wrong with this repo, I am sure all of those sites would host warnings about me...

So, short story: Open source has some potential for malicious code, but the open source community is strong and very quick to keep everyone in check and protect the users: And there are steps you can take to prevent your system from being compromised.

**Comment by firatuzman** [comment]
@clinton-hall Thank you for your mindful words. Sickrage is not root, but has privilege over the NAS. I should only mount tvshows and movies to my media pc and leave other stuff, pictures memories etc. elsewhere. Now its not the case...
Back to sickrage. It is a very sad story. I read what both had to say. I will not comment on what has happened. I had to migrate to the new sickrage repo after the old one (sickragetv) began suffering major faults these days.
Nzbtomedia functions properly after the migration without any changes on settings.

**Comment by rolandoldengarm** [comment]
@clinton-hall  I did as you suggested (update from GIT), but still get the error Failed to post-process. SickBeard does not support failed downloads!
I'm using sickrage on an ubuntu box
