### ISSUE TITLE
Failed to extract strange behavior

### ISSUE THREAD

**Issue by Sidhy** [clinton-hall/nzbToMedia#934]
nzbToSickBeard has strange behavior when rar is corrupted it keeps trying on all parts while it already failed on 1 of the parts. 

I deleted the files half way. added a custom line to mark where I deleted the files

log http://pastebin.com/PgBJcYaP

**Comment by jangrewe** [comment]
Same here!

**Comment by clinton-hall** [comment]
Thanks for reporting. I'll need to play and find a way to stop this...

**Comment by Boobybandit** [comment]
Hi there, same for me. What's odd is that the files can be manually repaired and extracted. Might be that uploaders are using a different version of winrar or something? When opening the par files in multipar, if the download is not damaged, it will always need to be renamed before I can extract the files. Is it possible that no check is performed on rename?

**Comment by clinton-hall** [comment]
What renaming is required and how do you know what to rename from/to?

**Comment by Boobybandit** [comment]
Just had one this afternoon. Was in doubt whether to post with example. But the last few months a lot of scene releases have been encrypted and renamed. 

So for example, you want to download serie.s01e02. It is renamed to "jWMD4xoRS3waV7sOr9MPgY5yk4CGsdkFWsfVIdwJS.mkv"
They the rar the file to "jWMD4xoRS3waV7sOr9MPgY5yk4CGsdkFWsfVIdwJS.partxx" and create a par file with it.
After that they rename the entire batch of rars and par to I2mKa87AtAJCwRW4d6TCXPQHZsZBmZKfV0GcCbqzS3sE.partxx

It is not possible to just extract the files at that point without first renaming with the par file (because the first rar will never find the second part which has a different name)! 

This results in me having a folder with only rar files, instead of a mkv. I then open the par file and multipar then renames the entire batch. After that I unrar and manually postprocess the file. 

I will try and post a real life example this weekend with screenshot and log attached. Realizing now that this is probably not the same issue as Sidhy meant. Worth a new issue?

**Comment by clinton-hall** [comment]
I should be able to accommodate this. But to be able to rename automatically, I need to have access to the correct names etc... I gather from the above, this required parsing the .par file?

**Comment by Boobybandit** [comment]
Yeah, the par file, when opened contains the correct names. To be honest, when I last used Newsleecher it wasn't able to handle these also. Had to manually process them. 

So I would think that a possible solution could be to trigger a repair/rename when extraction fails or so? Actually I don't know whether Sabnzbd extracts or Nzbtomedia does. I'll post a piece of my log here. As you can see, it says that no media file was found. However, the rar files are all present...

[11:10:14] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[11:10:17] [WARNING]::MAIN: Data from SABnzbd could not be parsed
[11:10:17] [INFO]::MAIN: Auto-detected SECTION:SickBeard
/usr/local/sbin/7z
/usr/local/sbin/7z
/usr/local/sbin/7z
[11:10:18] [INFO]::MAIN: Calling SickBeard:tv to post-process:SERIE.S03E02.1080p.HDTV.X264-DIMENSION.nzb
[11:10:26] [INFO]::MAIN: Attempting to auto-detect tv fork
[11:10:37] [INFO]::MAIN: SickBeard:tv fork auto-detection successful ...
[11:10:37] [INFO]::MAIN: SickBeard:tv fork set to sickrage
**[11:10:38] [WARNING]::SICKBEARD: No media files found in directory **/share/Download/sabnzbd/complete/SERIE.S03E02.1080p.HDTV.X264-DIMENSION. Processing this as a failed download

**Comment by daibakes** [comment]
Also running in to this. I can see from the log that the parts are failing but it goes through each part and so backs everything up.

**Comment by Boobybandit** [comment]
Wow so much dedication @clinton-hall   You are awesome!
