### ISSUE TITLE
Failed Support for SickGear

### ISSUE THREAD

**Issue by sea3pea0** [clinton-hall/nzbToMedia#971]
Hi I tried to set up failed downloads with nzbget and sickgear but had no luck. In the logs I see a message saying this fork of sickbeard doesn't support failed, though it does. Is there anyway you will support this fork? 

Thanks

**Comment by clinton-hall** [comment]
where have you downloaded SickGear from? I'll need to see what this fork uses.

Please also ensure that in SickGear, settings, search, the option to `Use Failed Downloads` is enabled.

**Comment by sea3pea0** [comment]
I am on their latest dev branch at https://github.com/SickGear/SickGear . I do have those settings set appropriately as well as the ones in nzbget according to what your wiki says. Thanks for looking into it for me clinton.. :)

**Comment by clinton-hall** [comment]
can you please enable debug logging, then show the log after a post-process attempt?

Also, if you go to sickgear web UI and then go to `/home/postprocess/` can you list all of the options that are displayed?

**Comment by sea3pea0** [comment]
[Here](http://i.imgur.com/c3RxMJU.png?1) is what /home/postprocess/ looks like. Here are the logs from nzbget for the last failed episode (I wasn't able to find anything relevant in sickgear at the corresponding time):

INFO	Mon Feb 22 2016 00:49:24	Collection The.Late.Show.with.Stephen.Colbert.2016.02.18.Tea.Leoni.720p.CBS.WEBRip.AAC2.0.x264-RTN added to history
ERROR	Mon Feb 22 2016 00:49:23	Post-process-script nzbToMedia/nzbToSickBeard.py for The.Late.Show.with.Stephen.Colbert.2016.02.18.Tea.Leoni.720p.CBS.WEBRip.AAC2.0.x264-RTN failed
INFO	Mon Feb 22 2016 00:49:23	nzbToSickBeard: SickBeard: Failed to post-process. SickBeard does not support failed downloads!
WARNING	Mon Feb 22 2016 00:49:23	Marking The.Late.Show.with.Stephen.Colbert.2016.02.18.Tea.Leoni.720p.CBS.WEBRip.AAC2.0.x264-RTN as bad
INFO	Mon Feb 22 2016 00:49:23	nzbToSickBeard: [00:49:23] [ERROR]::MAIN: A problem was reported in the /usr/local/nzbget/share/nzbget/scripts/nzbToMedia/nzbToSickBeard.py script.
INFO	Mon Feb 22 2016 00:49:22	nzbToSickBeard: [00:49:22] [INFO]::MAIN: Deleting /volume1/download/incomplete/The.Late.Show.with.Stephen.Colbert.2016.02.18.Tea.Leoni.720p.CBS.WEBRip.AAC2.0.x264-RTN.#245
INFO	Mon Feb 22 2016 00:49:22	nzbToSickBeard: [00:49:22] [POSTPROCESS]::SICKBEARD: Deleting failed files and folder /volume1/download/incomplete/The.Late.Show.with.Stephen.Colbert.2016.02.18.Tea.Leoni.720p.CBS.WEBRip.AAC2.0.x264-RTN.#245
INFO	Mon Feb 22 2016 00:49:22	nzbToSickBeard: [00:49:22] [POSTPROCESS]::SICKBEARD: FAILED: The download failed. custom branch does not handle failed downloads. Nothing to process
INFO	Mon Feb 22 2016 00:49:16	nzbToSickBeard: [00:49:16] [INFO]::MAIN: Sending failure notification to indexer site
INFO	Mon Feb 22 2016 00:49:16	nzbToSickBeard: [00:49:16] [WARNING]::SICKBEARD: No media files found in directory /volume1/download/incomplete/The.Late.Show.with.Stephen.Colbert.2016.02.18.Tea.Leoni.720p.CBS.WEBRip.AAC2.0.x264-RTN.#245. Processing this as a failed download

[Here](https://gist.github.com/sea3pea0/1338b2d3f5f366df9511) are the logs from a successful post process.

**Comment by Amelandbor** [comment]
Same problem here, after looking into the code it seems to me the problem is the detection of the fork.

This is in the log of nzbget:
SickBeard:tv fork auto-detection found custom params {'force': None, 'failed': None, 'process_method': None, 'dir': None}

These are not the exact same constants of any of the forks in [core/__init__.py](https://github.com/clinton-hall/nzbToMedia/blob/c50957d0b4683a125df039329d8f90df630d4e28/core/__init__.py#L50)

In [autoProcessTV.py](https://github.com/clinton-hall/nzbToMedia/blob/c50957d0b4683a125df039329d8f90df630d4e28/core/autoProcess/autoProcessTV.py#L245) it seems that it's only processed if it's in the _SICKBEARD_FAILED_ forks.

@clinton-hall 
There seem three ways to tackle this to me, create Sickgear in core/__init__.py, only look for failed in core/__init__.py to determine whether a branch handles failed downloads or use the failed fork parameter in autoProcessTV.py.

I can make a PR if you want and if the above assessment is right :)

**Comment by clinton-hall** [comment]
@Amelandbor 

A pull request to nightly would be greatly received.

Adding SickGear to init.py will help, but I think the best thing here is to remove the whole `SICKBEARD_FAILED` definition and instead just check for the `failed` parameter in autoProcessTV.py

This will be more reliable...

If you can do a PR that would be great, otherwise I'll try and look into this sometime this week.
